services:
  api:
    image: jsankare/honks-api:${TAG:-latest}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  web:
    image: jsankare/honks-web:${TAG:-latest}
    ports:
      # internal port 3000
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped

  mobile:
    image: jsankare/honks-app:${TAG:-latest}
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
