# Les valeurs doivent être en base64
kubectl create secret generic honks-secrets \
--from-literal=MONGO_PASSWORD=<ton_mot_de_passe> \
--from-literal=MONGO_ROOT_PASSWORD=<root_password> \
--from-literal=JWT_SECRET=<jwt_secret> \
-n honks-app